language: python
python:
  - 2.7
notifications:
  email: false

# Setup anaconda
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose dateutil
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - travis_retry pip install -r requirements.txt
  - python setup.py install
 
# Run test
script:
  - source bin/cpu_env.sh
  # - export THEANO_FLAGS="$THEANO_FLAGS,blas.ldflags='-lblas -lgfortran'"
  - nosetests --logging-level=INFO
  # Coverage test
  # - nosetests --with-cov --cover-tests deepy --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc